### ISSUE TITLE
addFlight User (Backend)

### ISSUE THREAD

**Issue by alyyasser19** [alyyasser19/MightyDucks#36]
The System should take the list already initialized for users and add the flight to it, then update it.

this works only for N users. checks should be taken into consideration such as the existance of the flights already, if the type of user is N, etc...

**Comment by alyyasser19** [comment]
the flight should be added as a JSON including but not limited to the following items.
list of names of travlers departure and return flights, including the dates and times of the departure and return flights, the chosen cabin (Economy/ Business Class), the chosen seat and the total price paid for the entire ticket along with a unique booking number

**Comment by alyyasser19** [comment]
Backend should generate a unique booking number

**Comment by alyyasser19** [comment]
an email should be sent to the user  once the booking is done

**Comment by faridasamer** [comment]
The format for flights would be json file that has: departure, return, no of passengers(list of persons with their cabin class, baggage (tbd))

**Comment by alyyasser19** [comment]
and price paid
